/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWarehousesRouteImport } from './routes/app.warehouses'
import { Route as AppVehiclesRouteImport } from './routes/app.vehicles'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppTripsRouteImport } from './routes/app.trips'
import { Route as AppTrackingRouteImport } from './routes/app.tracking'
import { Route as AppSystemOwnerRouteImport } from './routes/app.system-owner'
import { Route as AppShipmentsRouteImport } from './routes/app.shipments'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMaintenanceRouteImport } from './routes/app.maintenance'
import { Route as AppKpiRouteImport } from './routes/app.kpi'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppFuelRouteImport } from './routes/app.fuel'
import { Route as AppFinanceRouteImport } from './routes/app.finance'
import { Route as AppDriversRouteImport } from './routes/app.drivers'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppContractsRouteImport } from './routes/app.contracts'
import { Route as AppAccidentsRouteImport } from './routes/app.accidents'
import { Route as ApiPublicHooksScanAlertsRouteImport } from './routes/api.public.hooks.scan-alerts'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWarehousesRoute = AppWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AppRoute,
} as any)
const AppVehiclesRoute = AppVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTripsRoute = AppTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingRoute = AppTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemOwnerRoute = AppSystemOwnerRouteImport.update({
  id: '/system-owner',
  path: '/system-owner',
  getParentRoute: () => AppRoute,
} as any)
const AppShipmentsRoute = AppShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceRoute = AppMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppKpiRoute = AppKpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppFuelRoute = AppFuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDriversRoute = AppDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsRoute = AppContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AppRoute,
} as any)
const AppAccidentsRoute = AppAccidentsRouteImport.update({
  id: '/accidents',
  path: '/accidents',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHooksScanAlertsRoute =
  ApiPublicHooksScanAlertsRouteImport.update({
    id: '/api/public/hooks/scan-alerts',
    path: '/api/public/hooks/scan-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/driver': typeof DriverRoute
  '/portal': typeof PortalRoute
  '/app/accidents': typeof AppAccidentsRoute
  '/app/contracts': typeof AppContractsRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/drivers': typeof AppDriversRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/fuel': typeof AppFuelRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/kpi': typeof AppKpiRoute
  '/app/maintenance': typeof AppMaintenanceRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shipments': typeof AppShipmentsRoute
  '/app/system-owner': typeof AppSystemOwnerRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app/trips': typeof AppTripsRoute
  '/app/users': typeof AppUsersRoute
  '/app/vehicles': typeof AppVehiclesRoute
  '/app/warehouses': typeof AppWarehousesRoute
  '/app/': typeof AppIndexRoute
  '/api/public/hooks/scan-alerts': typeof ApiPublicHooksScanAlertsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/driver': typeof DriverRoute
  '/portal': typeof PortalRoute
  '/app/accidents': typeof AppAccidentsRoute
  '/app/contracts': typeof AppContractsRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/drivers': typeof AppDriversRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/fuel': typeof AppFuelRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/kpi': typeof AppKpiRoute
  '/app/maintenance': typeof AppMaintenanceRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shipments': typeof AppShipmentsRoute
  '/app/system-owner': typeof AppSystemOwnerRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app/trips': typeof AppTripsRoute
  '/app/users': typeof AppUsersRoute
  '/app/vehicles': typeof AppVehiclesRoute
  '/app/warehouses': typeof AppWarehousesRoute
  '/app': typeof AppIndexRoute
  '/api/public/hooks/scan-alerts': typeof ApiPublicHooksScanAlertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/driver': typeof DriverRoute
  '/portal': typeof PortalRoute
  '/app/accidents': typeof AppAccidentsRoute
  '/app/contracts': typeof AppContractsRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/drivers': typeof AppDriversRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/fuel': typeof AppFuelRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/kpi': typeof AppKpiRoute
  '/app/maintenance': typeof AppMaintenanceRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shipments': typeof AppShipmentsRoute
  '/app/system-owner': typeof AppSystemOwnerRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app/trips': typeof AppTripsRoute
  '/app/users': typeof AppUsersRoute
  '/app/vehicles': typeof AppVehiclesRoute
  '/app/warehouses': typeof AppWarehousesRoute
  '/app/': typeof AppIndexRoute
  '/api/public/hooks/scan-alerts': typeof ApiPublicHooksScanAlertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/driver'
    | '/portal'
    | '/app/accidents'
    | '/app/contracts'
    | '/app/customers'
    | '/app/documents'
    | '/app/drivers'
    | '/app/finance'
    | '/app/fuel'
    | '/app/invoices'
    | '/app/kpi'
    | '/app/maintenance'
    | '/app/notifications'
    | '/app/orders'
    | '/app/reports'
    | '/app/settings'
    | '/app/shipments'
    | '/app/system-owner'
    | '/app/tracking'
    | '/app/trips'
    | '/app/users'
    | '/app/vehicles'
    | '/app/warehouses'
    | '/app/'
    | '/api/public/hooks/scan-alerts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/driver'
    | '/portal'
    | '/app/accidents'
    | '/app/contracts'
    | '/app/customers'
    | '/app/documents'
    | '/app/drivers'
    | '/app/finance'
    | '/app/fuel'
    | '/app/invoices'
    | '/app/kpi'
    | '/app/maintenance'
    | '/app/notifications'
    | '/app/orders'
    | '/app/reports'
    | '/app/settings'
    | '/app/shipments'
    | '/app/system-owner'
    | '/app/tracking'
    | '/app/trips'
    | '/app/users'
    | '/app/vehicles'
    | '/app/warehouses'
    | '/app'
    | '/api/public/hooks/scan-alerts'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/driver'
    | '/portal'
    | '/app/accidents'
    | '/app/contracts'
    | '/app/customers'
    | '/app/documents'
    | '/app/drivers'
    | '/app/finance'
    | '/app/fuel'
    | '/app/invoices'
    | '/app/kpi'
    | '/app/maintenance'
    | '/app/notifications'
    | '/app/orders'
    | '/app/reports'
    | '/app/settings'
    | '/app/shipments'
    | '/app/system-owner'
    | '/app/tracking'
    | '/app/trips'
    | '/app/users'
    | '/app/vehicles'
    | '/app/warehouses'
    | '/app/'
    | '/api/public/hooks/scan-alerts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  DriverRoute: typeof DriverRoute
  PortalRoute: typeof PortalRoute
  ApiPublicHooksScanAlertsRoute: typeof ApiPublicHooksScanAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/warehouses': {
      id: '/app/warehouses'
      path: '/warehouses'
      fullPath: '/app/warehouses'
      preLoaderRoute: typeof AppWarehousesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vehicles': {
      id: '/app/vehicles'
      path: '/vehicles'
      fullPath: '/app/vehicles'
      preLoaderRoute: typeof AppVehiclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trips': {
      id: '/app/trips'
      path: '/trips'
      fullPath: '/app/trips'
      preLoaderRoute: typeof AppTripsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tracking': {
      id: '/app/tracking'
      path: '/tracking'
      fullPath: '/app/tracking'
      preLoaderRoute: typeof AppTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/system-owner': {
      id: '/app/system-owner'
      path: '/system-owner'
      fullPath: '/app/system-owner'
      preLoaderRoute: typeof AppSystemOwnerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shipments': {
      id: '/app/shipments'
      path: '/shipments'
      fullPath: '/app/shipments'
      preLoaderRoute: typeof AppShipmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/maintenance': {
      id: '/app/maintenance'
      path: '/maintenance'
      fullPath: '/app/maintenance'
      preLoaderRoute: typeof AppMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kpi': {
      id: '/app/kpi'
      path: '/kpi'
      fullPath: '/app/kpi'
      preLoaderRoute: typeof AppKpiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fuel': {
      id: '/app/fuel'
      path: '/fuel'
      fullPath: '/app/fuel'
      preLoaderRoute: typeof AppFuelRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/drivers': {
      id: '/app/drivers'
      path: '/drivers'
      fullPath: '/app/drivers'
      preLoaderRoute: typeof AppDriversRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contracts': {
      id: '/app/contracts'
      path: '/contracts'
      fullPath: '/app/contracts'
      preLoaderRoute: typeof AppContractsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accidents': {
      id: '/app/accidents'
      path: '/accidents'
      fullPath: '/app/accidents'
      preLoaderRoute: typeof AppAccidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/scan-alerts': {
      id: '/api/public/hooks/scan-alerts'
      path: '/api/public/hooks/scan-alerts'
      fullPath: '/api/public/hooks/scan-alerts'
      preLoaderRoute: typeof ApiPublicHooksScanAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAccidentsRoute: typeof AppAccidentsRoute
  AppContractsRoute: typeof AppContractsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppDriversRoute: typeof AppDriversRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppFuelRoute: typeof AppFuelRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppKpiRoute: typeof AppKpiRoute
  AppMaintenanceRoute: typeof AppMaintenanceRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShipmentsRoute: typeof AppShipmentsRoute
  AppSystemOwnerRoute: typeof AppSystemOwnerRoute
  AppTrackingRoute: typeof AppTrackingRoute
  AppTripsRoute: typeof AppTripsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppVehiclesRoute: typeof AppVehiclesRoute
  AppWarehousesRoute: typeof AppWarehousesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccidentsRoute: AppAccidentsRoute,
  AppContractsRoute: AppContractsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppDriversRoute: AppDriversRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppFuelRoute: AppFuelRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppKpiRoute: AppKpiRoute,
  AppMaintenanceRoute: AppMaintenanceRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShipmentsRoute: AppShipmentsRoute,
  AppSystemOwnerRoute: AppSystemOwnerRoute,
  AppTrackingRoute: AppTrackingRoute,
  AppTripsRoute: AppTripsRoute,
  AppUsersRoute: AppUsersRoute,
  AppVehiclesRoute: AppVehiclesRoute,
  AppWarehousesRoute: AppWarehousesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  DriverRoute: DriverRoute,
  PortalRoute: PortalRoute,
  ApiPublicHooksScanAlertsRoute: ApiPublicHooksScanAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
